export const gachaCharToElement = {
    "Albedo": "Geo",
    "Alhaitham": "Dendro",
    "Aloy": "Cryo",
    "Amber": "Pyro",
    "Arataki Itto": "Geo",
    "Baizhu": "Dendro",
    "Barbara": "Hydro",
    "Beidou": "Electro",
    "Bennett": "Pyro",
    "Candace": "Hydro",
    "Chongyun": "Cryo",
    "Collei": "Dendro",
    "Cyno": "Electro",
    "Dehya": "Pyro",
    "Diluc": "Pyro",
    "Diona": "Cryo",
    "Dori": "Electro",
    "Eula": "Cryo",
    "Faruzan": "Anemo",
    "Fischl": "Electro",
    "Ganyu": "Cryo",
    "Gorou": "Geo",
    "Hu Tao": "Pyro",
    "Jean": "Anemo",
    "Kaedehara Kazuha": "Anemo",
    "Kaeya": "Cryo",
    "Kamisato Ayaka": "Cryo",
    "Kamisato Ayato": "Hydro",
    "Kaveh": "Dendro",
    "Keqing": "Electro",
    "Kirara": "Dendro",
    "Klee": "Pyro",
    "Kujou Sara": "Electro",
    "Kuki Shinobu": "Electro",
    "Layla": "Cryo",
    "Lisa": "Electro",
    "Mika": "Cryo",
    "Mona": "Hydro",
    "Nahida": "Dendro",
    "Nilou": "Hydro",
    "Ningguang": "Geo",
    "Noelle": "Geo",
    "Qiqi": "Cryo",
    "Raiden Shogun": "Electro",
    "Razor": "Electro",
    "Rosaria": "Cryo",
    "Sangonomiya Kokomi": "Hydro",
    "Sayu": "Anemo",
    "Shenhe": "Cryo",
    "Shikanoin Heizou": "Anemo",
    "Sucrose": "Anemo",
    "Tartaglia": "Hydro",
    "Thoma": "Pyro",
    "Tighnari": "Dendro",
    "Venti": "Anemo",
    "Wanderer": "Anemo",
    "Xiangling": "Pyro",
    "Xiao": "Anemo",
    "Xingqiu": "Hydro",
    "Xinyan": "Pyro",
    "Yae Miko": "Electro",
    "Yanfei": "Pyro",
    "Yaoyao": "Dendro",
    "Yelan": "Hydro",
    "Yoimiya": "Pyro",
    "Yun Jin": "Geo",
    "Zhongli": "Geo",
};
